### ISSUE TITLE
Please include actual license text

### ISSUE THREAD

**Issue by mtasaka** [toy/image_size#14]
Now I am considering to package this and redistribute this on Fedora project, I want to clarify the license of this software. Would you include actual license text?

Especially, I want to know what "Ruby's license" says here.
* Looks like this software was firstly released on 2010/Nov, at this time the license of Ruby was GPLv2 or "Ruby".
* The license of Ruby changed on the version of 1.9.3 to BSDL or "Ruby": https://www.ruby-lang.org/en/news/2011/08/01/ruby-1-9-3-preview1-has-been-released/ , which was on 2011/Aug, so I am not sure under which this software is licensed.
* Also, the term "Ruby's licence" is somewhat ambiguous. Someone interprets this as dual license, while other interprets this as "Ruby" license (as a *narrow* meaning): note https://spdx.org/licenses/Ruby.html seems to interpret "Ruby's license" as a narrow meaning.

So to clarify this, would you include actual license text? Thank you.

**Comment by toy** [comment]
Thank you for opening the issue!
My favourite category of questions ;)

I just wrote to the original author to clarify in hope that email still exists.

I forked the project from rubyforge with last release on 2007-05-16: https://web.archive.org/web/20140520001541/https://rubyforge.org/frs/?group_id=3460&release_id=11735 and license is only mentioned in readme, there is no file or anything else.
You are completely right about the change of Ruby license, so if I don't get an answer I think the right way would probably be to assume the GPLv2/Ruby license (https://svn.ruby-lang.org/repos/ruby/tags/v1_8_6/COPYING).

**Comment by mtasaka** [comment]
@lastshogun13 I assume you are the original author. Would you clarify what you intended for the original license? (Sorry if it is not you.)

**Comment by toy** [comment]
My email got bounced and I got no reply from most probably [his twitter](https://twitter.com/gawgaw61). We can wait, but it seems better to go with Ruby/GPLv2 and change if I get a reply, so please have a look at [license branch](https://github.com/toy/image_size/compare/license).

**Comment by toy** [comment]
@mtasaka ^^

**Comment by lastshogun13** [comment]
Sorry late reply.

I wrote this code a long time ago, so I've forgotten a lot.
I think to this library's original license is GPLv2/Ruby license.

**Comment by toy** [comment]
This issue fell out of my sight, I will release 132fbc810628707df14d601f6a61c905ac67575c in few days if there are no more comments

**Comment by toy** [comment]
@mtasaka Released as part of v2.1.1
